description: Secret, credential, and leak discovery

flags:
  - passive
  - safe

modules:
  - github_codesearch
  - github_org
  - trufflehog
  - git
  - leaks
  - filedownload
  - pastebin
  - hunterio
  - emails
  - employee_profiles
  - dehashed
  - gitlab
  - github_workflows
  

output_modules:
  - asset_inventory
  - neo4j

config:
  modules:
    github_codesearch:
      limit: 100
    trufflehog:
      only_verified: true
    leaks:
      max_age_days: 30
  scope:
    report_distance: 0
