# NOTICE: THESE ENTRIES ARE COMMENTED BY DEFAULT
# Please be sure to uncomment when inserting API keys, etc.
# interactsh_token: null
modules:
  bevigil:
    api_key: 'OBaQAasVxkIcKwav'
  credshed:
    username: ''
    password: ''
  fullhunt:
    api_key: '5010ca08-9f1f-4097-b97d-6f7303f63085'
  virustotal:
    api_key: '9ac070ba3bb4942ccb09f74dc7aa729dee6905680030c336ad2608f8a9b9a7f7'
  shodan_dns:
    api_key: '0KCigMk2GIKg7HNoRxpcqGDwgBRgOpjF'
  ip2location:
    api_key: '7994A77853D52E8B5B0BC930E9AE2738'
  wpscan:
    api_key: '2f4BC7jnxxVmrKE1d07GmGfXqpqtlKWzmJys03k3aok'
  binaryedge:
    api_key: ''
  passivetotal:
    api_key: ''
  gitlab:
    api_key: ''
  trickest:
    api_key: '99c18ad859ab72083ffc756628128e4da6f708e5'
  subdomainradar:
    api_key: ''
  chaos:
    api_key: 'e041c43c-4c6b-4b9a-8a1e-356e3121718b'
  securitytrails:
    api_key: 'MjE27RZyE13ifVynVmAUD_y7gLCqAN_A'
  builtwith:
    api_key: 'f3bc6136-2c06-485e-ba72-7b9e1dbc1341'
  c99:
    api_key: ''
  postman_download:
    api_key: ''
  git_clone:
    api_key: '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'
  hunterio:
    api_key: 'c5cd80b520d316170cea42c680582fe46dafdea3'
  postman:
    api_key: 'PMAK-680988dff686e80001fc5cdc-ab13a544a6b4d56c302f176d6ad7670b25'
  ipstack:
    api_key: 'd7c39fccca836795f5984077644afa50'
  leakix:
    api_key: 'KbffZUAoYqIFUhFANPDvJYaDsNCrh_X1VH5MXGZrnEyu4ihF'
  github_codesearch:
    api_key: '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'
  dehashed:
    username: 'bashguru@pm.me'
    api_key: '4712a7177f6ac94b21a7'
  bufferoverrun:
    api_key: ''
  censys:
    api_key: '54200199-296e-45dd-bd1f-c6dad9fcddd9'
  zoomeye:
    api_key: ''
  github_workflows:
    api_key: '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'
  github_org:
    api_key: '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'
  neo4j:
    username: neo4j
    password: bbotislife
  http:
    username: ''
    password: ''
  postgres:
    username: postgres
    password: bbotislife
  splunk:
    hectoken: ''
  mysql:
    username: root
    password: bbotislife
  websocket:
    token: ''